//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPakistan.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_areas
    {
        public int id { get; set; }
        public string area_name { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
