//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PingPakistan.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string text { get; set; }
        public Nullable<bool> is_approved { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> agree_count { get; set; }
        public Nullable<int> disagree_count { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
    }
}
